export enum Genres {
  Action = "Action",
  Adult = "Adult",
  Adventure = "Adventure",
  Animation = "Animation",
  Biography = "Biography",
  Comedy = "Comedy",
  Crime = "Crime",
  Documentary = "Documentary",
  Drama = "Drama",
  Family = "Family",
  Fantasy = "Fantasy",
  History = "History",
  Music = "Music",
  Musical = "Musical",
  Mystery = "Mystery",
  News = "News",
  Reality_Tv = "Reality_Tv",
  Romance = "Romance",
  SciFi = "SciFi",
  Short = "Short",
  Sport = "Sport",
  Talk_Show = "Talk_Show",
  Thriller = "Thriller",
  War = "War",
  Western = "Western"
}
